version: "3.9"

services:
  mongodb:
    image: mongo
    container_name: mongodb
    networks:
      - mern-network
    ports:
      - "27017:27017"

  server:
    build: ./server
    container_name: server
    ports:
      - "5000:5000"
    networks:
      - mern-network
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/employees

  client:
    build: ./client
    container_name: client
    ports:
      - "3000:3000"
    networks:
      - mern-network
    depends_on:
      - server

networks:
  mern-network:
    driver: bridge
